### ISSUE TITLE
Vulnerability analysis failed: module 'plistlib' has no attribute 'Data'

### ISSUE THREAD

**Issue by jufelvi** [talos-security/SEBASTiAn#1]
When executing the script, there is the follow error:
Vulnerability analysis failed: module 'plistlib' has no attribute 'Data'

I post here the complete response:

26/04/2023 17:56:28> [INFO][SEBASTiAn.analysis.IOSAnalysis][initialize()] Analyzing iOS application '*********************************'
26/04/2023 17:56:28> [CRITICAL][SEBASTiAn.main][perform_analysis_without_timeout()] Vulnerability analysis failed: module 'plistlib' has no attribute 'Data'
26/04/2023 17:56:28> [INFO][SEBASTiAn.main][perform_analysis_without_timeout()] 0 vulnerabilities checked before failure: 
26/04/2023 17:56:28> [INFO][SEBASTiAn.main][perform_analysis_without_timeout()] 0 vulnerabilities found before failure
26/04/2023 17:56:28> [INFO][SEBASTiAn.analysis.IOSAnalysis][finalize()] Deleting intermediate files generated during the iOS analysis
pebble.common.RemoteTraceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/biplist/__init__.py", line 126, in readPlist
    result = reader.parse()
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/biplist/__init__.py", line 234, in parse
    return self.readRoot()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/biplist/__init__.py", line 248, in readRoot
    raise NotBinaryPlistException()
biplist.NotBinaryPlistException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/biplist/__init__.py", line 141, in readPlist
    result = wrapDataObject(result, for_binary=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/biplist/__init__.py", line 154, in wrapDataObject
    elif isinstance(o, (bytes, plistlib.Data)) and for_binary:
                               ^^^^^^^^^^^^^
AttributeError: module 'plistlib' has no attribute 'Data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pebble/common.py", line 174, in process_execute
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/SEBASTIANTOOL/SEBASTiAn/src/SEBASTiAn/main.py", line 89, in perform_analysis_without_timeout
    analysis.initialize()
  File "/home/kali/SEBASTIANTOOL/SEBASTiAn/src/SEBASTiAn/analysis.py", line 314, in initialize
    self.bin_path, self.plist_readable = util.unpack_ios_app(
                                         ^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/SEBASTIANTOOL/SEBASTiAn/src/SEBASTiAn/util.py", line 101, in unpack_ios_app
    plist_readable = readPlist(os.path.join(output_dir, "Info.plist"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/biplist/__init__.py", line 143, in readPlist
    raise InvalidPlistException(e)
biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kali/SEBASTIANTOOL/SEBASTiAn/src/cli.py", line 117, in <module>
    main()
  File "/home/kali/SEBASTIANTOOL/SEBASTiAn/src/cli.py", line 92, in main
    vuln_json_dict = perform_analysis_with_timeout(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/SEBASTIANTOOL/SEBASTiAn/src/SEBASTiAn/main.py", line 192, in perform_analysis_with_timeout
    ).result()
      ^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'

**Comment by 0xdad0** [comment]
I conducted an investigation, and it appears that the issue is associated with plistlib rather than SEBASTiAn.
